name: docker-test-app

services:
  client:
    image: docker-test-image
    container_name: docker-test-client
    ports:
      - "5000:8080"
    depends_on:
      sql:
        condition: service_healthy
        restart: true
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: docker-test-sql
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=VeryStrongPW3!
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "$${SA_PASSWORD}" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s