name: docker-test-app

services:
  client:
    image: docker-test-image
    container_name: docker-test-client
    ports:
      - "5000:8080"
    environment:
      - DOCKERTEST_DB_SERVER=${DOCKERTEST_DB_SERVER}
      - DOCKERTEST_DB_USERNAME=${DOCKERTEST_DB_USERNAME}
      - DOCKERTEST_DB_PASSWORD=${DOCKERTEST_DB_PASSWORD}
    depends_on:
      sql:
        condition: service_healthy
        restart: true
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: docker-test-sql
    volumes:
      - sqldata:/var/opt/mssql
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=${DOCKERTEST_DB_PASSWORD}
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "$${MSSQL_SA_PASSWORD}" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  sqldata:
